---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cars":
    parameters:
    - name: cars
      in: path
      description: cars
      required: true
      schema:
        type: string
    get:
      summary: list cars
      responses:
        '200':
          description: successful
    post:
      summary: create car
      responses:
        '200':
          description: successful
  "/cars/new":
    get:
      summary: new car
      responses:
        '200':
          description: successful
  "/cars/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show car
      responses:
        '200':
          description: successful
    delete:
      summary: delete car
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: https://fast-lane-racers.onrender.com
